import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays } from 'lucide-react';
import { summariesService } from '../services/summaries';
import { PageHero } from '../components/layout/PageHero';
import { PageShell } from '../components/layout/PageShell';
import { Pagination } from '../components/Pagination';
import { SkeletonList, EmptyState, ErrorBanner } from '../components/ui/FeedbackStates';

export const WeeklySummariesPage: React.FC = () => {
  const [offset, setOffset] = useState(0);
  const limit = 12;
  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ['summaries', 'weekly', offset],
    queryFn: () => summariesService.listWeekly(limit, offset),
  });

  return (
    <PageShell>
      <PageHero
        title="Weekly Summaries"
        subtitle="Phase 1 weekly snapshots generated by backend jobs."
      />

      {isLoading ? (
        <SkeletonList rows={4} />
      ) : isError ? (
        <ErrorBanner
          message="Failed to load weekly summaries. Please try again."
          onRetry={() => void refetch()}
        />
      ) : data?.items?.length ? (
        <>
          <div className="space-y-4">
            {data.items.map((item) => (
              <article
                key={item.public_id}
                className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 shadow-lg shadow-black/10"
              >
                <div className="mb-4 flex items-start justify-between gap-4">
                  <div>
                    <h2 className="font-semibold text-white">
                      Week of{' '}
                      {!Number.isNaN(new Date(`${item.week_start}T00:00:00Z`).getTime())
                        ? new Date(`${item.week_start}T00:00:00Z`).toLocaleDateString(undefined, {
                            dateStyle: 'medium',
                            timeZone: 'UTC',
                          })
                        : 'N/A'}
                    </h2>
                    <p className="mt-1 text-xs text-slate-500">
                      Generated{' '}
                      {!Number.isNaN(new Date(item.generated_at).getTime())
                        ? new Date(item.generated_at).toLocaleString()
                        : 'N/A'}
                    </p>
                  </div>
                </div>
                <div className="grid gap-3 md:grid-cols-3">
                  <JsonBox title="Todo" value={item.todo_summary} />
                  <JsonBox title="Spending" value={item.spending_summary} />
                  <JsonBox title="Investing" value={item.investing_summary} />
                </div>
              </article>
            ))}
          </div>
          <div className="mt-5">
            <Pagination
              total={data.total}
              limit={data.limit}
              offset={data.offset}
              onPageChange={setOffset}
            />
          </div>
        </>
      ) : (
        <EmptyState
          icon={<CalendarDays className="h-6 w-6" />}
          title="No weekly summaries yet"
          description="Weekly summaries are automatically generated by backend jobs after activity is recorded for a full week."
        />
      )}
    </PageShell>
  );
};

const JsonBox = ({ title, value }: { title: string; value: Record<string, unknown> }) => (
  <div className="rounded-xl border border-slate-700 bg-slate-800/40 p-4">
    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">{title}</p>
    <pre className="overflow-auto rounded-lg bg-slate-950/50 p-2 text-xs text-slate-200">
      {JSON.stringify(value, null, 2)}
    </pre>
  </div>
);
